services:
  web:
    build: ./
    volumes:
      - ../:/var/www/html/
    ports:
      - 80:80
  
  db:
    image: mysql:latest
    volumes:
      - ../db:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db